name: jobprogress
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43Ï€
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 3.38.0+303800008

environment:
  sdk: ">=3.1.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.7.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.0
  device_info_plus: ^11.1.1
  fluttertoast: 8.2.12
  flutter_svg: ^2.0.16
  printing: ^5.13.4
  open_file_plus:
    git:
      url: https://github.com/manveer-logiciel/open_file_plus.git
      ref: main
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  jiffy: ^6.3.2
  flutter_widget_from_html_core: ^0.15.2
  flutter_simple_calculator: ^2.2.4
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: v6.2.0-beta.3
      path: flutter_inappwebview
  flutter_native_splash: ^2.3.4
  cached_network_image: ^3.3.0
  timezone: ^0.10.0
  sticky_headers: ^0.3.0
  easy_mask: ^2.0.1
  firebase_core: ^3.10.1
  firebase_database: ^11.3.1
  firebase_crashlytics: ^4.3.1
  firebase_messaging: ^15.2.1
  image_picker: ^1.0.4
  file_picker: ^8.3.1
  flutter_doc_scanner: ^0.0.16
  animations: ^2.0.8
  jpeg_encode: ^1.0.1
  scroll_to_index: ^3.0.1
  geolocator: ^13.0.2
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  connectivity_plus: ^6.1.2
  linked_scroll_controller: ^0.2.0
  flutter_local_notifications: ^19.3.0
  responsive_framework: 0.2.0
  sms_mms: ^0.0.3
  mixpanel_flutter: ^2.0.0
  flutter_slidable: ^3.0.0
  permission_handler: ^11.0.1
  http_mock_adapter: ^0.6.0
  google_maps_flutter: ^2.10.0
  flutter_contacts: ^1.1.7
  math_expressions: ^2.4.0
  image_gallery_saver_plus: ^3.0.5
  flutter_exif_rotation: 0.5.2
  flutter_dynamic_icon_plus: ^1.3.1
  flutter_sharing_intent: ^1.1.1
  launchdarkly_flutter_client_sdk: ^4.9.0
  pendo_sdk: 3.7.0
  flutter_google_places_sdk: ^0.4.2+1
  jp_mobile_flutter_ui:
    git:
      url: https://github.com/manveer-logiciel/jp-mobile-ui-kit-private.git
      ref: develop
  flutter_udid: ^3.0.0
  decimal: ^3.2.1
  geocoding: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  integration_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
#  husky: ^0.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/qb/
    - assets/images/hover/
    - assets/images/eagleview/
    - assets/images/quick_measure/
    - assets/images/skymeasure/
    - assets/html/
    - assets/html/img/
    - assets/html/fonts/
    - assets/html/template.js
    - assets/justifi/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages