name: 'Setup Android Build Environment'
description: 'Sets up Android SDK, Java, caching, and build configuration'

inputs:
  java-version:
    description: 'Java version to install'
    required: true
    default: '17'
  release-tag:
    description: 'Release tag for version configuration'
    required: true
  android-keystore-base64:
    description: 'Base64 encoded Android keystore'
    required: true
  android-store-password:
    description: 'Android keystore password'
    required: true
  android-key-password:
    description: 'Android key password'
    required: true
  android-key-alias:
    description: 'Android key alias'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
    
    - name: Cache Android Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android
        key: android-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-v4
        restore-keys: |
          android-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-
          android-${{ runner.os }}-
    
    - name: Cache Ruby & Fastlane
      uses: actions/cache@v4
      with:
        path: |
          android/vendor/bundle
          ~/.gem
          ~/.bundle
        key: ruby-android-${{ runner.os }}-${{ hashFiles('android/Gemfile.lock') }}-v4
        restore-keys: |
          ruby-android-${{ runner.os }}-${{ hashFiles('android/Gemfile') }}-
          ruby-android-${{ runner.os }}-
    
    - name: Setup Android Environment
      shell: bash
      run: |
        source scripts/setup-android.sh
        setup_android_environment "${{ inputs.release-tag }}"
      env:
        ANDROID_KEYSTORE_BASE64: ${{ inputs.android-keystore-base64 }}
        ANDROID_STORE_PASSWORD: ${{ inputs.android-store-password }}
        ANDROID_KEY_PASSWORD: ${{ inputs.android-key-password }}
        ANDROID_KEY_ALIAS: ${{ inputs.android-key-alias }}
