name: 'Setup Flutter Environment'
description: 'Sets up Flutter with caching and private repository access'

inputs:
  flutter-version:
    description: 'Flutter version to install'
    required: true
  private-token:
    description: 'Token for private repository access'
    required: false
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''

outputs:
  cache-hit:
    description: 'Whether Flutter cache was hit'
    value: ${{ steps.cache-flutter.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Cache Flutter Dependencies
      id: cache-flutter
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: flutter-${{ runner.os }}-${{ inputs.flutter-version }}-${{ hashFiles('**/pubspec.lock') }}${{ inputs.cache-key-suffix }}-v4
        restore-keys: |
          flutter-${{ runner.os }}-${{ inputs.flutter-version }}-${{ hashFiles('**/pubspec.lock') }}-
          flutter-${{ runner.os }}-${{ inputs.flutter-version }}-
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'
        cache: true
    
    - name: Configure Git for private repos
      if: inputs.private-token != ''
      shell: bash
      run: |
        git config --global url."https://x-access-token:${{ inputs.private-token }}@github.com/".insteadOf "https://github.com/"
    
    - name: Get Flutter dependencies
      shell: bash
      run: flutter pub get
