import 'common/meta_mock_response.dart';

class CustomerListingMockResponse {

  static const Map<String,dynamic> okResponse = {
    "data": [
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User2",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User3",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User4",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User5",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User6",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User7",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User8",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User9",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User10",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
    ],
    "params":{
      "includes":[
        "address",
        "phones",
        "appointments",
        "flags",
        "referred_by",
        "custom_fields",
        "flags.color"
      ],
      "is_optimized":"1",
      "limit":"20",
      "page":"1",
      "sort_by":"created_at",
      "sort_order":"desc"
    },
    "meta":MetaMockResponse.value,
    "status":200
  };

  static const Map<String,dynamic> okResponse2 = {
    "data": [
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User11",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User12",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User13",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User14",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User15",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User16",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User17",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User18",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User19",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User20",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
    ],
    "params":{
      "includes":[
        "address",
        "phones",
        "appointments",
        "flags",
        "referred_by",
        "custom_fields",
        "flags.color"
      ],
      "is_optimized":"1",
      "limit":"20",
      "page":"1",
      "sort_by":"created_at",
      "sort_order":"desc"
    },
    "meta":MetaMockResponse.value,
    "status":200
  };

  static const Map<String,dynamic> noDataResponse = {
    "data": <List<dynamic>>[],
    "meta": {
      "pagination":{
        "total":0,
        "count":0,
        "per_page":10,
        "current_page":1,
        "total_pages":1,
      }
    },
    "status":200
  };

  static const Map<String,dynamic> okResponseLastModified = {
    "data": [
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User20",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User19",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User18",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User17",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User16",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User15",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User14",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User13",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User12",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
      {
        "id":19644,
        "company_name":"",
        "address_id":76282,
        "billing_address_id":76282,
        "first_name":"Demo",
        "last_name":"User",
        "full_name":"Demo User11",
        "full_name_mobile":"Demo User",
        "email":"",
        "source_type":null,
        "additional_emails":<Null>[],
        "rep_id":null,
        "distance":null,
        "referred_by_type":"",
        "referred_by_note":"",
        "jobs_count":null,
        "call_required":false,
        "appointment_required":false,
        "note":"",
        "is_commercial":0,
        "created_at":"2022-12-08 04:25:40",
        "deleted_at":null,
        "management_company":"",
        "property_name":"",
        "quickbook_id":null,
        "canvasser_type":null,
        "canvasser":null,
        "call_center_rep_type":null,
        "call_center_rep":null,
        "quickbook_sync_status":null,
        "disable_qbo_sync":0,
        "origin":"JobProgress",
        "qb_desktop_id":null,
        "bid_customer":0,
        "is_prime_contractor_customer":0,
        "disable_qbo_financial_syncing":false,
        "address":{
          "id":76282,
          "address":"",
          "address_line_1":"",
          "city":"",
          "state_id":0,
          "state":null,
          "country_id":1,
          "country":{
            "id":1,
            "name":"United States",
            "code":"US",
            "currency_name":"Doller",
            "currency_symbol":"\$",
            "phone_code":"+91"
          },
          "zip":null,
          "lat":null,
          "long":null,
          "geocoding_error":1,
          "created_by":1229,
          "updated_by":1229,
          "update_origin":null,
          "updated_from":null,
          "device_uuid":null,
          "created_at":"2022-12-08 04:25:40",
          "updated_at":"2022-12-08 04:27:01"
        },
        "phones":{
          "data":[
            {
              "label":"cell",
              "number":1111111111,
              "ext":''
            }
          ]
        },
        "flags":{
          "data":<Null>[]
        },
        "custom_fields":{
          "data":<Null>[]
        }
      },
    ],
    "params":{
      "includes":[
        "address",
        "phones",
        "appointments",
        "flags",
        "referred_by",
        "custom_fields",
        "flags.color"
      ],
      "is_optimized":"1",
      "limit":"20",
      "page":"1",
      "sort_by":"created_at",
      "sort_order":"desc"
    },
    "meta":MetaMockResponse.value,
    "status":200
  };
}