class FeatureFlagMockResponse {
  static const Map<String,dynamic> okResponse = {
    "data":[
      {
        "feature":"production",
        "flag":1
      },
      {
        "feature":"reports",
        "flag":1
      },
      {
        "feature":"third_party_integrations",
        "flag":1
      },
      {
        "feature":"user_management",
        "flag":1
      },
      {
        "feature":"finance_and_accounting",
        "flag":1
      },
      {
        "feature":"material_labor_library",
        "flag":1
      },
      {
        "feature":"misc_features",
        "flag":1
      },
      {
        "feature":"documents",
        "flag":1
      },
      {
        "feature":"customer_job_features",
        "flag":1
      },
      {
        "feature":"automation",
        "flag":1
      }
    ],
    "status":200
  };
}
