class StatesMockResponse {

  static const Map<String,dynamic> okResponse = {
    "data":[
      {
        "id":1,
        "name":"Alabama",
        "code":"AL",
        "country_id":1
      },
      {
        "id":2,
        "name":"Alaska",
        "code":"AK",
        "country_id":1
      },
      {
        "id":3,
        "name":"Arizona",
        "code":"AZ",
        "country_id":1
      },
      {
        "id":4,
        "name":"Arkansas",
        "code":"AR",
        "country_id":1
      },
      {
        "id":5,
        "name":"California",
        "code":"CA",
        "country_id":1
      },
      {
        "id":6,
        "name":"Colorado",
        "code":"CO",
        "country_id":1
      },
      {
        "id":7,
        "name":"Connecticut",
        "code":"CT",
        "country_id":1
      },
      {
        "id":8,
        "name":"Delaware",
        "code":"DE",
        "country_id":1
      },
      {
        "id":9,
        "name":"Florida",
        "code":"FL",
        "country_id":1
      },
      {
        "id":10,
        "name":"Georgia",
        "code":"GA",
        "country_id":1
      },
      {
        "id":11,
        "name":"Hawaii",
        "code":"HI",
        "country_id":1
      },
      {
        "id":12,
        "name":"Idaho",
        "code":"ID",
        "country_id":1
      },
      {
        "id":13,
        "name":"Illinois",
        "code":"IL",
        "country_id":1
      },
      {
        "id":14,
        "name":"Indiana",
        "code":"IN",
        "country_id":1
      },
      {
        "id":15,
        "name":"Iowa",
        "code":"IA",
        "country_id":1
      },
      {
        "id":16,
        "name":"Kansas",
        "code":"KS",
        "country_id":1
      },
      {
        "id":17,
        "name":"Kentucky",
        "code":"KY",
        "country_id":1
      },
      {
        "id":18,
        "name":"Louisiana",
        "code":"LA",
        "country_id":1
      },
      {
        "id":19,
        "name":"Maine",
        "code":"ME",
        "country_id":1
      },
      {
        "id":20,
        "name":"Maryland",
        "code":"MD",
        "country_id":1
      },
      {
        "id":21,
        "name":"Massachusetts",
        "code":"MA",
        "country_id":1
      },
      {
        "id":22,
        "name":"Michigan",
        "code":"MI",
        "country_id":1
      },
      {
        "id":23,
        "name":"Minnesota",
        "code":"MN",
        "country_id":1
      },
      {
        "id":24,
        "name":"Mississippi",
        "code":"MS",
        "country_id":1
      },
      {
        "id":25,
        "name":"Missouri",
        "code":"MO",
        "country_id":1
      },
      {
        "id":26,
        "name":"Montana",
        "code":"MT",
        "country_id":1
      },
      {
        "id":27,
        "name":"Nebraska",
        "code":"NE",
        "country_id":1
      },
      {
        "id":28,
        "name":"Nevada",
        "code":"NV",
        "country_id":1
      },
      {
        "id":29,
        "name":"New Hampshire",
        "code":"NH",
        "country_id":1
      },
      {
        "id":30,
        "name":"New Jersey",
        "code":"NJ",
        "country_id":1
      },
      {
        "id":31,
        "name":"New Mexico",
        "code":"NM",
        "country_id":1
      },
      {
        "id":32,
        "name":"New York",
        "code":"NY",
        "country_id":1
      },
      {
        "id":33,
        "name":"North Carolina",
        "code":"NC",
        "country_id":1
      },
      {
        "id":34,
        "name":"North Dakota",
        "code":"ND",
        "country_id":1
      },
      {
        "id":35,
        "name":"Ohio",
        "code":"OH",
        "country_id":1
      },
      {
        "id":36,
        "name":"Oklahoma",
        "code":"OK",
        "country_id":1
      },
      {
        "id":37,
        "name":"Oregon",
        "code":"OR",
        "country_id":1
      },
      {
        "id":38,
        "name":"Pennsylvania",
        "code":"PA",
        "country_id":1
      },
      {
        "id":39,
        "name":"Rhode Island",
        "code":"RI",
        "country_id":1
      },
      {
        "id":40,
        "name":"South Carolina",
        "code":"SC",
        "country_id":1
      },
      {
        "id":41,
        "name":"South Dakota",
        "code":"SD",
        "country_id":1
      },
      {
        "id":42,
        "name":"Tennessee",
        "code":"TN",
        "country_id":1
      },
      {
        "id":43,
        "name":"Texas",
        "code":"TX",
        "country_id":1
      },
      {
        "id":44,
        "name":"Utah",
        "code":"UT",
        "country_id":1
      },
      {
        "id":45,
        "name":"Vermont",
        "code":"VT",
        "country_id":1
      },
      {
        "id":46,
        "name":"Virginia",
        "code":"VA",
        "country_id":1
      },
      {
        "id":47,
        "name":"Washington",
        "code":"WA",
        "country_id":1
      },
      {
        "id":48,
        "name":"West Virginia",
        "code":"WV",
        "country_id":1
      },
      {
        "id":49,
        "name":"Wisconsin",
        "code":"WI",
        "country_id":1
      },
      {
        "id":50,
        "name":"Wyoming",
        "code":"WY",
        "country_id":1
      },
      {
        "id":51,
        "name":"Washington D.C.",
        "code":"WDC",
        "country_id":1
      },
      {
        "id":52,
        "name":"Bahamas",
        "code":"BHS",
        "country_id":2
      },
      {
        "id":53,
        "name":"Alberta",
        "code":"AB",
        "country_id":4
      },
      {
        "id":54,
        "name":"British Columbia",
        "code":"BC",
        "country_id":4
      },
      {
        "id":55,
        "name":"Manitoba",
        "code":"MB",
        "country_id":4
      },
      {
        "id":56,
        "name":"New Brunswick",
        "code":"NB",
        "country_id":4
      },
      {
        "id":57,
        "name":"Newfoundland and Labrador",
        "code":"NL",
        "country_id":4
      },
      {
        "id":58,
        "name":"Nova Scotia",
        "code":"NS",
        "country_id":4
      },
      {
        "id":59,
        "name":"Northwest Territories",
        "code":"NT",
        "country_id":4
      },
      {
        "id":60,
        "name":"Nunavut",
        "code":"NU",
        "country_id":4
      },
      {
        "id":61,
        "name":"Ontario",
        "code":"ON",
        "country_id":4
      },
      {
        "id":62,
        "name":"Prince Edward Island",
        "code":"PE",
        "country_id":4
      },
      {
        "id":63,
        "name":"Quebec",
        "code":"QC",
        "country_id":4
      },
      {
        "id":64,
        "name":"Saskatchewan",
        "code":"SK",
        "country_id":4
      },
      {
        "id":65,
        "name":"Yukon",
        "code":"YT",
        "country_id":4
      },
      {
        "id":66,
        "name":"Aberdeenshire",
        "code":"ABD",
        "country_id":5
      },
      {
        "id":67,
        "name":"Alderney",
        "code":"ALD",
        "country_id":5
      },
      {
        "id":68,
        "name":"Anglesey",
        "code":"AGY",
        "country_id":5
      },
      {
        "id":69,
        "name":"Angus",
        "code":"ANS",
        "country_id":5
      },
      {
        "id":70,
        "name":"Argyllshire",
        "code":"ARL",
        "country_id":5
      },
      {
        "id":71,
        "name":"Avon",
        "code":"AVN",
        "country_id":5
      },
      {
        "id":72,
        "name":"Ayrshire",
        "code":"AYR",
        "country_id":5
      },
      {
        "id":73,
        "name":"Banffshire",
        "code":"BAN",
        "country_id":5
      },
      {
        "id":74,
        "name":"Bedfordshire",
        "code":"BDF",
        "country_id":5
      },
      {
        "id":75,
        "name":"Berkshire",
        "code":"BRK",
        "country_id":5
      },
      {
        "id":76,
        "name":"Berwickshire",
        "code":"BEW",
        "country_id":5
      },
      {
        "id":77,
        "name":"Borders",
        "code":"BOR",
        "country_id":5
      },
      {
        "id":78,
        "name":"Breconshire",
        "code":"BRE",
        "country_id":5
      },
      {
        "id":79,
        "name":"Buckinghamshire",
        "code":"BKM",
        "country_id":5
      },
      {
        "id":80,
        "name":"Bute",
        "code":"BUT",
        "country_id":5
      },
      {
        "id":81,
        "name":"Caernarvonshire",
        "code":"CAE",
        "country_id":5
      },
      {
        "id":82,
        "name":"Caithness",
        "code":"CAI",
        "country_id":5
      },
      {
        "id":83,
        "name":"Cambridgeshire",
        "code":"CAM",
        "country_id":5
      },
      {
        "id":84,
        "name":"Cardiganshire",
        "code":"CGN",
        "country_id":5
      },
      {
        "id":85,
        "name":"Carmarthenshire",
        "code":"CMN",
        "country_id":5
      },
      {
        "id":86,
        "name":"Central",
        "code":"CEN",
        "country_id":5
      },
      {
        "id":87,
        "name":"Cheshire",
        "code":"CHS",
        "country_id":5
      },
      {
        "id":88,
        "name":"Clackmannanshire",
        "code":"CLK",
        "country_id":5
      },
      {
        "id":89,
        "name":"Cleveland",
        "code":"CLV",
        "country_id":5
      },
      {
        "id":90,
        "name":"Clwyd",
        "code":"CWD",
        "country_id":5
      },
      {
        "id":91,
        "name":"Co. Antrim",
        "code":"ANT",
        "country_id":5
      },
      {
        "id":92,
        "name":"Co. Armagh",
        "code":"ARM",
        "country_id":5
      },
      {
        "id":93,
        "name":"Co. Carlow",
        "code":"CAR",
        "country_id":5
      },
      {
        "id":94,
        "name":"Co. Cavan",
        "code":"CAV",
        "country_id":5
      },
      {
        "id":95,
        "name":"Co. Clare",
        "code":"CLA",
        "country_id":5
      },
      {
        "id":96,
        "name":"Co. Cork",
        "code":"COR",
        "country_id":5
      },
      {
        "id":97,
        "name":"Co. Donegal",
        "code":"DON",
        "country_id":5
      },
      {
        "id":98,
        "name":"Co. Down",
        "code":"DOW",
        "country_id":5
      },
      {
        "id":99,
        "name":"Co. Dublin",
        "code":"DUB",
        "country_id":5
      },
      {
        "id":100,
        "name":"Co. Durham",
        "code":"DUR",
        "country_id":5
      },
      {
        "id":101,
        "name":"Co. Fermanagh",
        "code":"FER",
        "country_id":5
      },
      {
        "id":102,
        "name":"Co. Galway",
        "code":"GAL",
        "country_id":5
      },
      {
        "id":103,
        "name":"Co. Kerry",
        "code":"KER",
        "country_id":5
      },
      {
        "id":104,
        "name":"Co. Kildare",
        "code":"KID",
        "country_id":5
      },
      {
        "id":105,
        "name":"Co. Kilkenny",
        "code":"KIK",
        "country_id":5
      },
      {
        "id":106,
        "name":"Co. Laois",
        "code":"LEX",
        "country_id":5
      },
      {
        "id":107,
        "name":"Co. Leitrim",
        "code":"LET",
        "country_id":5
      },
      {
        "id":108,
        "name":"Co. Limerick",
        "code":"LIM",
        "country_id":5
      },
      {
        "id":109,
        "name":"Co. Londonderry",
        "code":"LDY",
        "country_id":5
      },
      {
        "id":110,
        "name":"Co. Longford",
        "code":"LOG",
        "country_id":5
      },
      {
        "id":111,
        "name":"Co. Louth",
        "code":"LOU",
        "country_id":5
      },
      {
        "id":112,
        "name":"Co. Mayo",
        "code":"MAY",
        "country_id":5
      },
      {
        "id":113,
        "name":"Co. Meath",
        "code":"MEA",
        "country_id":5
      },
      {
        "id":114,
        "name":"Co. Monaghan",
        "code":"MOG",
        "country_id":5
      },
      {
        "id":115,
        "name":"Co. Offaly",
        "code":"OFF",
        "country_id":5
      },
      {
        "id":116,
        "name":"Co. Roscommon",
        "code":"ROS",
        "country_id":5
      },
      {
        "id":117,
        "name":"Co. Sligo",
        "code":"SLI",
        "country_id":5
      },
      {
        "id":118,
        "name":"Co. Tipperary",
        "code":"TIP",
        "country_id":5
      },
      {
        "id":119,
        "name":"Co. Tyrone",
        "code":"TYR",
        "country_id":5
      },
      {
        "id":120,
        "name":"Co. Waterford",
        "code":"WAT",
        "country_id":5
      },
      {
        "id":121,
        "name":"Co. Westmeath",
        "code":"WEM",
        "country_id":5
      },
      {
        "id":122,
        "name":"Co. Wexford",
        "code":"WEX",
        "country_id":5
      },
      {
        "id":123,
        "name":"Co. Wicklow",
        "code":"WIC",
        "country_id":5
      },
      {
        "id":124,
        "name":"Cornwall",
        "code":"CON",
        "country_id":5
      },
      {
        "id":125,
        "name":"Cumberland",
        "code":"CUL",
        "country_id":5
      },
      {
        "id":126,
        "name":"Cumbria",
        "code":"CMA",
        "country_id":5
      },
      {
        "id":127,
        "name":"Denbighshire",
        "code":"DEN",
        "country_id":5
      },
      {
        "id":128,
        "name":"Derbyshire",
        "code":"DBY",
        "country_id":5
      },
      {
        "id":129,
        "name":"Devon",
        "code":"DEV",
        "country_id":5
      },
      {
        "id":130,
        "name":"Dorset",
        "code":"DOR",
        "country_id":5
      },
      {
        "id":131,
        "name":"Dumfries and Galloway",
        "code":"DGY",
        "country_id":5
      },
      {
        "id":132,
        "name":"Dumfries-shire",
        "code":"DFS",
        "country_id":5
      },
      {
        "id":133,
        "name":"Dunbartonshire",
        "code":"DNB",
        "country_id":5
      },
      {
        "id":134,
        "name":"Dyfed",
        "code":"DFD",
        "country_id":5
      },
      {
        "id":135,
        "name":"East Lothian",
        "code":"ELN",
        "country_id":5
      },
      {
        "id":136,
        "name":"East Riding of Yorkshire",
        "code":"ERY",
        "country_id":5
      },
      {
        "id":137,
        "name":"East Sussex",
        "code":"SXE",
        "country_id":5
      },
      {
        "id":138,
        "name":"Essex",
        "code":"ESS",
        "country_id":5
      },
      {
        "id":139,
        "name":"Fife",
        "code":"FIF",
        "country_id":5
      },
      {
        "id":140,
        "name":"Flintshire",
        "code":"FLN",
        "country_id":5
      },
      {
        "id":141,
        "name":"Glamorgan",
        "code":"GLA",
        "country_id":5
      },
      {
        "id":142,
        "name":"Gloucestershire",
        "code":"GLS",
        "country_id":5
      },
      {
        "id":143,
        "name":"Grampian",
        "code":"GMP",
        "country_id":5
      },
      {
        "id":144,
        "name":"Greater Manchester",
        "code":"GTM",
        "country_id":5
      },
      {
        "id":145,
        "name":"Guernsey",
        "code":"GSY",
        "country_id":5
      },
      {
        "id":146,
        "name":"Gwent",
        "code":"GNT",
        "country_id":5
      },
      {
        "id":147,
        "name":"Gwynedd",
        "code":"GWN",
        "country_id":5
      },
      {
        "id":148,
        "name":"Hampshire",
        "code":"HAM",
        "country_id":5
      },
      {
        "id":149,
        "name":"Hereford and Worcester",
        "code":"HWR",
        "country_id":5
      },
      {
        "id":150,
        "name":"Herefordshire",
        "code":"HEF",
        "country_id":5
      },
      {
        "id":151,
        "name":"Hertfordshire",
        "code":"HRT",
        "country_id":5
      },
      {
        "id":152,
        "name":"Highland",
        "code":"HLD",
        "country_id":5
      },
      {
        "id":153,
        "name":"Humberside",
        "code":"HUM",
        "country_id":5
      },
      {
        "id":154,
        "name":"Huntingdonshire",
        "code":"HUN",
        "country_id":5
      },
      {
        "id":155,
        "name":"Inverness-shire",
        "code":"INV",
        "country_id":5
      },
      {
        "id":156,
        "name":"Isle of Wight",
        "code":"IOW",
        "country_id":5
      },
      {
        "id":157,
        "name":"Jersey",
        "code":"JSY",
        "country_id":5
      },
      {
        "id":158,
        "name":"Kent",
        "code":"KEN",
        "country_id":5
      },
      {
        "id":159,
        "name":"Kincardineshire",
        "code":"KCD",
        "country_id":5
      },
      {
        "id":160,
        "name":"Kinross-shire",
        "code":"KRS",
        "country_id":5
      },
      {
        "id":161,
        "name":"Kirkcudbrightshire",
        "code":"KKD",
        "country_id":5
      },
      {
        "id":162,
        "name":"Lanarkshire",
        "code":"LKS",
        "country_id":5
      },
      {
        "id":163,
        "name":"Lancashire",
        "code":"LAN",
        "country_id":5
      },
      {
        "id":164,
        "name":"Leicestershire",
        "code":"LEI",
        "country_id":5
      },
      {
        "id":165,
        "name":"Lincolnshire",
        "code":"LIN",
        "country_id":5
      },
      {
        "id":166,
        "name":"Lothian",
        "code":"LTN",
        "country_id":5
      },
      {
        "id":167,
        "name":"Merionethshire",
        "code":"MER",
        "country_id":5
      },
      {
        "id":168,
        "name":"Merseyside",
        "code":"MSY",
        "country_id":5
      },
      {
        "id":169,
        "name":"Mid Glamorgan",
        "code":"MGM",
        "country_id":5
      },
      {
        "id":170,
        "name":"Midlothian",
        "code":"MLN",
        "country_id":5
      },
      {
        "id":171,
        "name":"Monmouthshire",
        "code":"MON",
        "country_id":5
      },
      {
        "id":172,
        "name":"Montgomeryshire",
        "code":"MGY",
        "country_id":5
      },
      {
        "id":173,
        "name":"Morayshire",
        "code":"MOR",
        "country_id":5
      },
      {
        "id":174,
        "name":"Nairn",
        "code":"NAI",
        "country_id":5
      },
      {
        "id":175,
        "name":"Norfolk",
        "code":"NFK",
        "country_id":5
      },
      {
        "id":176,
        "name":"North Riding of Yorkshire",
        "code":"NRY",
        "country_id":5
      },
      {
        "id":177,
        "name":"North Yorkshire",
        "code":"NYK",
        "country_id":5
      },
      {
        "id":178,
        "name":"Northamptonshire",
        "code":"NTH",
        "country_id":5
      },
      {
        "id":179,
        "name":"Northumberland",
        "code":"NBL",
        "country_id":5
      },
      {
        "id":180,
        "name":"Nottinghamshire",
        "code":"NTT",
        "country_id":5
      },
      {
        "id":181,
        "name":"Orkney",
        "code":"OKI",
        "country_id":5
      },
      {
        "id":182,
        "name":"Oxfordshire",
        "code":"OXF",
        "country_id":5
      },
      {
        "id":183,
        "name":"Peebles-shire",
        "code":"PEE",
        "country_id":5
      },
      {
        "id":184,
        "name":"Pembrokeshire",
        "code":"PEM",
        "country_id":5
      },
      {
        "id":185,
        "name":"Perth",
        "code":"PER",
        "country_id":5
      },
      {
        "id":186,
        "name":"Powys",
        "code":"POW",
        "country_id":5
      },
      {
        "id":187,
        "name":"Radnorshire",
        "code":"RAD",
        "country_id":5
      },
      {
        "id":188,
        "name":"Renfrewshire",
        "code":"RFW",
        "country_id":5
      },
      {
        "id":189,
        "name":"Ross and Cromarty",
        "code":"ROC",
        "country_id":5
      },
      {
        "id":190,
        "name":"Roxburghshire",
        "code":"ROX",
        "country_id":5
      },
      {
        "id":191,
        "name":"Rutland",
        "code":"RUT",
        "country_id":5
      },
      {
        "id":192,
        "name":"Sark",
        "code":"SRK",
        "country_id":5
      },
      {
        "id":193,
        "name":"Selkirkshire",
        "code":"SEL",
        "country_id":5
      },
      {
        "id":194,
        "name":"Shetland",
        "code":"SHI",
        "country_id":5
      },
      {
        "id":195,
        "name":"Shropshire",
        "code":"SAL",
        "country_id":5
      },
      {
        "id":196,
        "name":"Somerset",
        "code":"SOM",
        "country_id":5
      },
      {
        "id":197,
        "name":"South Glamorgan",
        "code":"SGM",
        "country_id":5
      },
      {
        "id":198,
        "name":"South Yorkshire",
        "code":"SYK",
        "country_id":5
      },
      {
        "id":199,
        "name":"Staffordshire",
        "code":"STS",
        "country_id":5
      },
      {
        "id":200,
        "name":"Stirlingshire",
        "code":"STI",
        "country_id":5
      },
      {
        "id":201,
        "name":"Strathclyde",
        "code":"STD",
        "country_id":5
      },
      {
        "id":202,
        "name":"Suffolk",
        "code":"SFK",
        "country_id":5
      },
      {
        "id":203,
        "name":"Surrey",
        "code":"SRY",
        "country_id":5
      },
      {
        "id":204,
        "name":"Sussex",
        "code":"SSX",
        "country_id":5
      },
      {
        "id":205,
        "name":"Sutherland",
        "code":"SUT",
        "country_id":5
      },
      {
        "id":206,
        "name":"Tayside",
        "code":"TAY",
        "country_id":5
      },
      {
        "id":207,
        "name":"Tyne and Wear",
        "code":"TWR",
        "country_id":5
      },
      {
        "id":208,
        "name":"Warwickshire",
        "code":"WAR",
        "country_id":5
      },
      {
        "id":209,
        "name":"West Glamorgan",
        "code":"WGM",
        "country_id":5
      },
      {
        "id":210,
        "name":"West Lothian",
        "code":"WLN",
        "country_id":5
      },
      {
        "id":211,
        "name":"West Midlands",
        "code":"WMD",
        "country_id":5
      },
      {
        "id":212,
        "name":"West Riding of Yorkshire",
        "code":"WRY",
        "country_id":5
      },
      {
        "id":213,
        "name":"West Sussex",
        "code":"SXW",
        "country_id":5
      },
      {
        "id":214,
        "name":"West Yorkshire",
        "code":"WYK",
        "country_id":5
      },
      {
        "id":215,
        "name":"Western Isles",
        "code":"WIS",
        "country_id":5
      },
      {
        "id":216,
        "name":"Westmorland",
        "code":"WES",
        "country_id":5
      },
      {
        "id":217,
        "name":"Wigtownshire",
        "code":"WIG",
        "country_id":5
      },
      {
        "id":218,
        "name":"Wiltshire",
        "code":"WIL",
        "country_id":5
      },
      {
        "id":219,
        "name":"Worcestershire",
        "code":"WOR",
        "country_id":5
      },
      {
        "id":220,
        "name":"Yorkshire",
        "code":"YKS",
        "country_id":5
      },
      {
        "id":221,
        "name":"New South Wales",
        "code":"NSW",
        "country_id":3
      },
      {
        "id":222,
        "name":"Queensland",
        "code":"QLD",
        "country_id":3
      },
      {
        "id":223,
        "name":"South Australia",
        "code":"SA",
        "country_id":3
      },
      {
        "id":224,
        "name":"Tasmania",
        "code":"TAS",
        "country_id":3
      },
      {
        "id":225,
        "name":"Victoria",
        "code":"VIC",
        "country_id":3
      },
      {
        "id":226,
        "name":"Western Australia",
        "code":"WA",
        "country_id":3
      },
      {
        "id":227,
        "name":"Australian Capital Territory",
        "code":"ACT",
        "country_id":3
      },
      {
        "id":228,
        "name":"Northern Territory",
        "code":"NT",
        "country_id":3
      },
      {
        "id":229,
        "name":"London",
        "code":"LND",
        "country_id":5
      },
      {
        "id":230,
        "name":"Puerto Rico",
        "code":"PR",
        "country_id":6
      }
    ],
    "status":200
  };
}