enum LocalDBOtherActions {
  getUsersWithTagsDivision,
  getDivisionsWithUsers,
  getTagsWithUsers,
  getReferrals,
  getTrades,
  getCompanies,
  getCountries,
  getStates,
  getFlags,
  getWorkflowStages,
  get1UserRecord,
  deleteDB,
  migrateOldDB,
}